INSERT INTO tbl_cards (hp, name, info, attack, damage, weak, resis, retreat, cardNumberInCollection, collection_id, type_id, stage_id)
VALUES
(50, 'Bulbasaur', 'Seed Pokémon', 'Leech Seed', '20', 'Fire', 'Water', '1 Colorless', 44, 1, 4, 1),
(60, 'Ivysaur', 'Seed Pokémon', 'Vine Whip', '30', 'Fire', 'Water', '2 Colorless', 30, 1, 4, 2),
(80, 'Charmander', 'Lizard Pokémon', 'Ember', '30', 'Water', 'Grass', '1 Colorless', 46, 1, 2, 1),
(90, 'Charmeleon', 'Flame Pokémon', 'Flamethrower', '50', 'Water', 'Grass', '2 Colorless', 24, 1, 2, 2),
(50, 'Squirtle', 'Tiny Turtle Pokémon', 'Bubble', '20', 'Electric', 'Steel', '1 Colorless', 63, 1, 3, 1),
(70, 'Wartortle', 'Turtle Pokémon', 'Withdraw', '—', 'Electric', 'Steel', '2 Colorless', 42, 1, 3, 2),
(40, 'Pidgey', 'Tiny Bird Pokémon', 'Gust', '10', 'Electric', 'Fighting', '1 Colorless', 57, 1, 5, 1),
(60, 'Pidgeotto', 'Bird Pokémon', 'Whirlwind', '20', 'Electric', 'Fighting', '1 Colorless', 17, 1, 5, 2),
(80, 'Pidgeot', 'Bird Pokémon', 'Hurricane', '30', 'Electric', 'Fighting', '2 Colorless', 22, 1, 5, 3),
(50, 'Rattata', 'Mouse Pokémon', 'Bite', '20', 'Fighting', 'Psychic', '1 Colorless', 61, 1, 5, 1),
(70, 'Raticate', 'Mouse Pokémon', 'Super Fang', '—', 'Fighting', 'Psychic', '2 Colorless', 40, 1, 5, 2),
(60, 'Nidoran♀', 'Poison Pin Pokémon', 'Scratch', '20', 'Psychic', 'Grass', '1 Colorless', 55, 1, 4, 1),
(70, 'Nidorina', 'Poison Pin Pokémon', 'Double Kick', '30x', 'Psychic', 'Grass', '2 Colorless', 36, 1, 4, 2),
(80, 'Nidoqueen', 'Drill Pokémon', 'Mega Punch', '40', 'Psychic', 'Grass', '3 Colorless', 12, 1, 4, 3),
(60, 'Nidoran♂', 'Poison Pin Pokémon', 'Horn Attack', '30', 'Psychic', 'Grass', '1 Colorless', 56, 1, 4, 1),
(70, 'Nidorino', 'Poison Pin Pokémon', 'Horn Drill', '50', 'Psychic', 'Grass', '2 Colorless', 37, 1, 4, 2),
(90, 'Nidoking', 'Drill Pokémon', 'Thrash', '30+', 'Psychic', 'Grass', '3 Colorless', 11, 1, 4, 3),
(50, 'Oddish', 'Weed Pokémon', 'Absorb', '10', 'Fire', 'Water', '1 Colorless', 59, 1, 4, 1),
(70, 'Gloom', 'Weed Pokémon', 'Poisonpowder', '20', 'Fire', 'Water', '2 Colorless', 38, 1, 4, 2),
(90, 'Vileplume', 'Flower Pokémon', 'Petal Dance', '40x', 'Fire', 'Water', '2 Colorless', 15, 1, 4, 3),
(60, 'Diglett', 'Mole Pokémon', 'Dig', '20', 'Grass', 'Electric', '1 Colorless', 47, 1, 7, 1),
(70, 'Dugtrio', 'Mole Pokémon', 'Earthquake', '70', 'Grass', 'Electric', '2 Colorless', 19, 1, 7, 2),
(50, 'Geodude', 'Rock Pokémon', 'Tackle', '20', 'Grass', 'Electric', '1 Colorless', 48, 1, 7, 1),
(70, 'Graveler', 'Rock Pokémon', 'Rock Throw', '40', 'Grass', 'Electric', '2 Colorless', 39, 1, 7, 2),
(90, 'Golem', 'Megaton Pokémon', 'Explosion', '100', 'Grass', 'Electric', '3 Colorless', 21, 1, 7, 3),
(60, 'Gastly', 'Gas Pokémon', 'Lick', '10', 'Psychic', 'Fighting', '1 Colorless', 49, 1, 6, 1),
(70, 'Haunter', 'Gas Pokémon', 'Hypnosis', '—', 'Psychic', 'Fighting', '2 Colorless', 25, 1, 6, 2),
(90, 'Alakazam', 'Psi Pokémon', 'Confuse Ray', '30', 'Psychic', 'Fighting', '3 Colorless', 1, 1, 6, 3),
(60, 'Onix', 'Rock Snake Pokémon', 'Rock Throw', '10', 'Grass', 'Electric', '1 Colorless', 56, 1, 7, 1),
(80, 'Chansey', 'Egg Pokémon', 'Double-Edge', '80', 'Fighting', 'Psychic', '1 Colorless', 3, 1, 5, 1);
