INSERT INTO tbl_cards (hp, name, info, attack, damage, weak, resis, retreat, cardNumberInCollection, collection_id, type_id, stage_id)
VALUES
(60, 'Clefairy', 'Fairy Pokémon', 'Sing', '—', 'Steel', 'Psychic', '1 Colorless', 5, 1, 5, 1),
(120, 'Clefable', 'Fairy Pokémon', 'Metronome', '—', 'Steel', 'Psychic', '2 Colorless', 6, 1, 5, 2),
(50, 'Ekans', 'Snake Pokémon', 'Wrap', '10', 'Psychic', 'Grass', '1 Colorless', 60, 1, 4, 1),
(70, 'Arbok', 'Cobra Pokémon', 'Poison Fang', '20', 'Psychic', 'Grass', '2 Colorless', 22, 1, 4, 2),
(40, 'Zubat', 'Bat Pokémon', 'Leech Life', '10', 'Psychic', 'Fighting', '1 Colorless', 62, 1, 6, 1),
(60, 'Golbat', 'Bat Pokémon', 'Wing Attack', '30', 'Psychic', 'Fighting', '2 Colorless', 33, 1, 6, 2),
(80, 'Paras', 'Mushroom Pokémon', 'Scratch', '20', 'Fire', 'Water', '1 Colorless', 64, 1, 4, 1),
(90, 'Parasect', 'Mushroom Pokémon', 'Spore', '—', 'Fire', 'Water', '2 Colorless', 26, 1, 4, 2),
(50, 'Meowth', 'Scratch Cat Pokémon', 'Pay Day', '10', 'Fighting', 'Psychic', '1 Colorless', 65, 1, 5, 1),
(70, 'Persian', 'Classy Cat Pokémon', 'Scratch', '20', 'Fighting', 'Psychic', '2 Colorless', 27, 1, 5, 2),
(60, 'Psyduck', 'Duck Pokémon', 'Headache', '—', 'Electric', 'Steel', '1 Colorless', 66, 1, 3, 1),
(80, 'Golduck', 'Duck Pokémon', 'Hyper Beam', '20', 'Electric', 'Steel', '2 Colorless', 28, 1, 3, 2),
(50, 'Mankey', 'Pig Monkey Pokémon', 'Scratch', '20', 'Psychic', 'Steel', '1 Colorless', 67, 1, 7, 1),
(80, 'Primeape', 'Pig Monkey Pokémon', 'Fury Swipes', '20x', 'Psychic', 'Steel', '2 Colorless', 34, 1, 7, 2),
(60, 'Growlithe', 'Puppy Pokémon', 'Flame Tail', '20', 'Water', 'Grass', '1 Colorless', 68, 1, 2, 1),
(90, 'Arcanine', 'Legendary Pokémon', 'Take Down', '50', 'Water', 'Grass', '2 Colorless', 23, 1, 2, 2),
(50, 'Poliwag', 'Tadpole Pokémon', 'Bubble', '10', 'Electric', 'Steel', '1 Colorless', 69, 1, 3, 1),
(70, 'Poliwhirl', 'Tadpole Pokémon', 'Amnesia', '20', 'Electric', 'Steel', '2 Colorless', 35, 1, 3, 2),
(90, 'Poliwrath', 'Tadpole Pokémon', 'Submission', '40', 'Electric', 'Steel', '3 Colorless', 13, 1, 3, 3),
(60, 'Tentacool', 'Jellyfish Pokémon', 'Acid', '10', 'Electric', 'Steel', '1 Colorless', 70, 1, 3, 1),
(80, 'Tentacruel', 'Jellyfish Pokémon', 'Supersonic', '—', 'Electric', 'Steel', '2 Colorless', 41, 1, 3, 2),
(50, 'Magnemite', 'Magnet Pokémon', 'Thunder Wave', '10', 'Fighting', 'Steel', '1 Colorless', 71, 1, 1, 1),
(70, 'Magneton', 'Magnet Pokémon', 'Selfdestruct', '80', 'Fighting', 'Steel', '2 Colorless', 9, 1, 1, 2),
(60, 'Farfetch’d', 'Wild Duck Pokémon', 'Leek Slap', '30', 'Electric', 'Steel', '1 Colorless', 72, 1, 5, 1),
(80, 'Doduo', 'Twin Bird Pokémon', 'Fury Attack', '10x', 'Electric', 'Fighting', '1 Colorless', 73, 1, 5, 1),
(90, 'Dodrio', 'Triple Bird Pokémon', 'Rage', '30+', 'Electric', 'Fighting', '2 Colorless', 18, 1, 5, 2),
(60, 'Seel', 'Sea Lion Pokémon', 'Headbutt', '20', 'Electric', 'Steel', '1 Colorless', 74, 1, 3, 1),
(80, 'Dewgong', 'Sea Lion Pokémon', 'Aurora Beam', '50', 'Electric', 'Steel', '2 Colorless', 26, 1, 3, 2),
(60, 'Grimer', 'Sludge Pokémon', 'Poison Gas', '10', 'Psychic', 'Fighting', '1 Colorless', 75, 1, 6, 1),
(80, 'Muk', 'Sludge Pokémon', 'Sludge', '30', 'Psychic', 'Fighting', '2 Colorless', 19, 1, 6, 2);
